### ISSUE TITLE
cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by pduchnovsky** [linuxserver/docker-pyload-ng#10] opened 2022-02-23 07:39 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
app should start up

## Current Behavior
app crashes

## Steps to Reproduce

1. start the :latest image

## Environment
**OS:** `Linux d-server 4.4.180+ #42218 SMP Mon Oct 18 19:16:55 CST 2021 x86_64 GNU/Linux synology_geminilake_920+`
**How docker service was installed:** Synology package manager

## Command used to create docker container (run/create/compose/screenshot)

```
version: '2.4'
services:
  pyload:
    image: linuxserver/pyload-ng
    container_name: pyload
    ports:
      - 8000:8000
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /volume1/docker/pyload:/config
    restart: always
```
## Docker logs

```
[2022-02-23 07:36:14]  INFO                pyload  *** Welcome to pyLoad 0.5.0 ***
[2022-02-23 07:36:14]  DEBUG               pyload  Indexing plugins...
[2022-02-23 07:36:14]  INFO                pyload  Activated plugins: ClickNLoad, ExternalScripts, TORRENT, UnSkipOnFail, UserAgentSwitcher
[2022-02-23 07:36:14]  INFO                pyload  Deactivate plugins: AndroidPhoneNotify, AntiCaptcha, AntiStandby, AntiVirus, AppriseNotify, BypassCaptcha, Captcha9Kw, Checksum, CloudFlareDdos, DeathByCaptcha, DeleteFinished, DiscordNotifier, DownloadScheduler, ExpertDecoders, ExtractArchive, HotFolder, IRC, ImageTyperz, JustPremium, LinkFilter, LinkdecrypterComHook, LogMarker, MergeFiles, MultiHome, PushBullet, PushOver, RestartFailed, SkipRev, TransmissionRPC, UpdateManager, WindowsPhoneNotify, XFileSharing, XMPP
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py)
Traceback (most recent call last):
  File "/usr/bin/pyload", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/pyload/__main__.py", line 293, in main
    run(core_args, args.daemon, args.pidfile)
  File "/usr/lib/python3.9/site-packages/pyload/__main__.py", line 236, in run
    pyload_core = Core(*core_args)
  File "/usr/lib/python3.9/site-packages/pyload/core/__init__.py", line 105, in __init__
    self._init_webserver()
  File "/usr/lib/python3.9/site-packages/pyload/core/__init__.py", line 168, in _init_webserver
    from pyload.webui.webserver_thread import WebServerThread
  File "/usr/lib/python3.9/site-packages/pyload/webui/webserver_thread.py", line 9, in <module>
    from .app import App
  File "/usr/lib/python3.9/site-packages/pyload/webui/app/__init__.py", line 13, in <module>
    import flask
  File "/usr/lib/python3.9/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
  File "/usr/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
Deleting old pidfile /tmp/pyLoad/pyload.pid
    from .environment import Environment
  File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py)
```

**Comment by Monirzadeh** [comment] 2022-02-23 08:12
just for confirm i have same problem today.

**Comment by savonarola27** [comment] 2022-02-23 09:04
The same for me. Revert to [0.5.0b3.dev13-ls5](https://github.com/linuxserver/docker-pyload-ng/releases/tag/0.5.0b3.dev13-ls5) and works again.

**Comment by gbutti13** [comment] 2022-02-24 08:52
same for me. Revert to [0.5.0b3.dev13-ls5]

**Comment by lduesing** [comment] 2022-02-27 17:54
https://github.com/pallets/markupsafe/issues/284
That's the problem

**Comment by eender** [comment] 2022-02-27 19:00
:latest ([0.5.0b3.dev13-ls6](https://github.com/linuxserver/docker-pyload-ng/releases/tag/0.5.0b3.dev13-ls6)) is still affected

**Comment by aptalca** [comment] 2022-02-27 19:31
Should be tracked upstream:
https://github.com/pyload/pyload/issues/4103

**Comment by eender** [comment] 2022-02-27 19:42
The workaround works for me: `python -m pip install markupsafe==2.0.1`.
Waiting for a fix. Thanks for the reopening.

**Comment by aptalca** [comment] 2022-02-27 23:03
@eender and others, can you test the `develop` tag? Upstream pushed a potential fix and we're trying to confirm.

Thanks

**Comment by eender** [comment] 2022-02-27 23:18
@aptalca I can confirm that this error is fixed with the latest develop tag

**Comment by aptalca** [comment] 2022-02-28 02:29
Latest build should be fixed now

**Closed by aptalca** 2022-02-28 02:29 UTC
